sky:
  smCrypt:
    publicKey: 04c7afd2cdad7a7e3d86c83fd689ef81c9e8941c2da1e410899dfa548fec6cbedbac9280785817de7ffb74dda3dad3232a8999d358e4301780063482ec182bc47a
    privateKey: d66a2b1f0c73376bc6ede79d0b64378d58c356fbf85800e9cbcd877510dc8cf8

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database0: 0
    database1: 1
    database2: 2
    database3: 3
    database4: 4
    database5: 5
    database6: 6
    database7: 7
    database8: 8
    database9: 9
    #连接超时时间（毫秒）
    timeout: 3000
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      maxActive: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      maxWait: -1
      # 连接池中的最大空闲连接
      maxIdle: 8
      # 连接池中的最小空闲连接
      minIdle: 0
  # 过滤器 放开拦截路径
  filter:
    openUri:
#      - /login
      - /register
      - /captchaImage
      - /auth/**
      - /user/findOne
      - /redis/**
      - /encrypt/**
      - /encrypt/user



